# Generated by Django 5.0.7 on 2024-07-17 12:42

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0003_remove_citymodel_user_citymodel_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='citymodel',
            name='user',
            field=models.ManyToManyField(related_name='cities', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
