# Generated by Django 5.0.7 on 2024-07-18 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0004_alter_citymodel_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymodel',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
