# Generated by Django 5.0.7 on 2024-07-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0005_citymodel_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='citymodel',
            name='searched',
            field=models.IntegerField(default=1),
        ),
    ]
